# Generated by Django 5.0.7 on 2024-11-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condiciones_PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo_pdf', models.FileField(upload_to='archivos_pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa_PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo_pdf', models.FileField(upload_to='archivos_pdf/')),
            ],
        ),
    ]
