# Generated by Django 5.0.7 on 2024-11-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifas_condiciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condiciones_pdf',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tarifa_pdf',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
