# Generated by Django 5.0.2 on 2025-03-28 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='category',
        ),
        migrations.AddField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/noticias'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
