# Generated by Django 6.0.2 on 2026-04-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='cctv_sistema_o',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='obs_sistema_o',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='presion_gh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='presion_gh_obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='rrhh_registros',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reporte',
            name='sistema_o',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='indicar_cual_cctv',
            field=models.CharField(blank=True, default='Todas apagadas', max_length=255),
        ),
    ]
