# Generated by Django 5.2.13 on 2026-04-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_reporte_cctv_sistema_o_reporte_obs_sistema_o_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='baliza_encendida_lomas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='baliza_encendida_lomas_acceso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='lomas_acceso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='obs_lomas_acceso',
            field=models.TextField(blank=True, null=True),
        ),
    ]
