# Generated by Django 5.2.13 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0003_reporte_baliza_encendida_lomas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporte",
            name="alarma_ugps_activa",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
