# Generated by Django 5.2.13 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0004_reporte_alarma_ugps_activa"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporte",
            name="planta_solar",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
