# Generated by Django 5.2.13 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0005_reporte_planta_solar"),
    ]

    operations = [
        migrations.CreateModel(
            name="RRHHPersonalVigente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("row_key", models.CharField(max_length=100, unique=True)),
                ("nombre_vigente", models.CharField(blank=True, default="", max_length=150)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Personal RRHH vigente",
                "verbose_name_plural": "Personal RRHH vigente",
                "ordering": ["row_key"],
            },
        ),
    ]
