# Generated by Django 5.2.13 on 2026-04-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0007_reporte_grabado_local"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reporte",
            name="grabado_local",
        ),
    ]
